In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
train_data = pd.read_csv("/content/train.csv")
test_data = pd.read_csv("/content/test.csv")
x_train = train_data.iloc[:,:-1]
y_train = train_data['Activity']
x_test = test_data.iloc[:,:-1]
y_test = test_data['Activity']

In [ ]:
missing_val = train_data.isnull().sum()
unique_lables = y_train.unique()

print(missing_val,unique_lables)

tBodyAcc-mean()-X       0
tBodyAcc-mean()-Y       0
tBodyAcc-mean()-Z       0
tBodyAcc-std()-X        0
tBodyAcc-std()-Y        0
                       ..
angle(X,gravityMean)    0
angle(Y,gravityMean)    0
angle(Z,gravityMean)    0
subject                 0
Activity                0
Length: 563, dtype: int64 ['STANDING' 'SITTING' 'LAYING' 'WALKING' 'WALKING_DOWNSTAIRS'
 'WALKING_UPSTAIRS']


In [ ]:
x_train = x_train.dropna(axis=1)
x_test = x_test.dropna(axis=1)

In [ ]:
#RANDOM FOREST CLASSIFIER
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

rf_classifier.fit(x_train, y_train)

y_pred = rf_classifier.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

conmat = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conmat)


Accuracy: 0.9267051238547676
Classification Report:
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.91      0.90      0.91       491
          STANDING       0.91      0.92      0.91       532
           WALKING       0.89      0.96      0.93       496
WALKING_DOWNSTAIRS       0.97      0.85      0.91       420
  WALKING_UPSTAIRS       0.88      0.91      0.90       471

          accuracy                           0.93      2947
         macro avg       0.93      0.92      0.92      2947
      weighted avg       0.93      0.93      0.93      2947

Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 440  51   0   0   0]
 [  0  41 491   0   0   0]
 [  0   0   0 476   5  15]
 [  0   0   0  21 358  41]
 [  0   0   0  36   6 429]]


In [ ]:
#SUPPORT VECTOR
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

# Initialize an SVM classifier
model = SVC()


model.fit(x_train, y_train)

# Predict on test set
y_pred = model.predict(x_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)

# Calculate confusion matrix and classification report
conmat = confusion_matrix(y_test, y_pred)
classification_report = classification_report(y_test, y_pred)

# Print results
print("Accuracy:", accuracy)
print("Confusion Matrix:")
print(conmat)
print("Classification Report:")
print(classification_report)

Accuracy: 0.9307770614183916
Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 421  68   0   0   2]
 [  0  45 487   0   0   0]
 [  0   0   0 494   2   0]
 [  0   0   0  33 358  29]
 [  0   0   0  23   2 446]]
Classification Report:
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.90      0.86      0.88       491
          STANDING       0.88      0.92      0.90       532
           WALKING       0.90      1.00      0.94       496
WALKING_DOWNSTAIRS       0.99      0.85      0.92       420
  WALKING_UPSTAIRS       0.94      0.95      0.94       471

          accuracy                           0.93      2947
         macro avg       0.93      0.93      0.93      2947
      weighted avg       0.93      0.93      0.93      2947



In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


logistic_regression_model = LogisticRegression(max_iter=1000)


logistic_regression_model.fit(x_train, y_train)


y_pred = logistic_regression_model.predict(x_test)


accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

# Generate confusion matrix
conmat = confusion_matrix(y_test, y_pred)

# Display confusion matrix a
print("Confusion Matrix:")
print(conmat)



Accuracy: 0.9599592806243638
Classification Report:
                    precision    recall  f1-score   support

            LAYING       1.00      1.00      1.00       537
           SITTING       0.98      0.87      0.92       491
          STANDING       0.89      0.98      0.93       532
           WALKING       0.94      0.99      0.97       496
WALKING_DOWNSTAIRS       0.99      0.97      0.98       420
  WALKING_UPSTAIRS       0.97      0.94      0.96       471

          accuracy                           0.96      2947
         macro avg       0.96      0.96      0.96      2947
      weighted avg       0.96      0.96      0.96      2947

Confusion Matrix:
[[537   0   0   0   0   0]
 [  0 425  63   0   0   3]
 [  0  10 522   0   0   0]
 [  0   0   0 493   3   0]
 [  0   0   0   3 407  10]
 [  0   0   0  26   0 445]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
#NAIVE BAYES CLASSIFIER
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
nb_classifier = GaussianNB()

nb_classifier.fit(x_train, y_train)


y_pred = nb_classifier.predict(x_test)

accuracy_nb = accuracy_score(y_test, y_pred)
print("Naive Bayes Accuracy:", accuracy_nb)

class_report_nb = classification_report(y_test, y_pred)
print("Naive Bayes Classification Report:")
print(class_report_nb)



Naive Bayes Accuracy: 0.7702748557855447
Naive Bayes Classification Report:
                    precision    recall  f1-score   support

            LAYING       0.96      0.61      0.75       537
           SITTING       0.58      0.73      0.65       491
          STANDING       0.79      0.87      0.83       532
           WALKING       0.82      0.84      0.83       496
WALKING_DOWNSTAIRS       0.83      0.61      0.70       420
  WALKING_UPSTAIRS       0.76      0.96      0.84       471

          accuracy                           0.77      2947
         macro avg       0.79      0.77      0.77      2947
      weighted avg       0.79      0.77      0.77      2947



In [ ]:
#HYPER PARAMETER TUNNING IN SVC
from sklearn.svm import SVC
from sklearn.model_selection import RandomizedSearchCV

# Define hyperparameter grid for SVM
param_grid_svm = {
    'C': [0.1, 1, 10, 100],
    'gamma': [0.1, 0.01, 0.001, 0.0001],
    'kernel': ['rbf', 'linear', 'poly', 'sigmoid']
}

# Initialize SVM classifier
svm_classifier = SVC()

random_search_svm = RandomizedSearchCV(estimator=svm_classifier, param_distributions=param_grid_svm, n_iter=100,
                                       cv=5, verbose=2, random_state=42, n_jobs=-1)

# Fit the random search to the data
random_search_svm.fit(x_train, y_train)

# Print the best parameters found
print("Best Parameters for SVM:", random_search_svm.best_params_)

# Print the best score found
print("Best Score for SVM:", random_search_svm.best_score_)


Fitting 5 folds for each of 64 candidates, totalling 320 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 64 is smaller than n_iter=100. Running 64 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Best Parameters for SVM: {'kernel': 'linear', 'gamma': 0.1, 'C': 1}
Best Score for SVM: 0.9360805042615279


In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Define the parameter grid to search
param_grid = {
    'logistic_regression__C': [0.001, 0.01, 0.1, 1, 10, 100],  # Regularization parameter
    'logistic_regression__penalty': ['l1', 'l2']  # Penalty norm
}

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logistic_regression', LogisticRegression(solver='liblinear', max_iter=1000))  # Solver supports both L1 and L2 regularization
])
grid_search = GridSearchCV(estimator=pipeline, param_grid=param_grid, cv=5, scoring='accuracy', verbose=1, n_jobs=-1)
grid_search.fit(x_train, y_train)

# Print the best hyperparameters found
print("Best Hyperparameters:", grid_search.best_params_)

# Get the best model
best_logistic_regression = grid_search.best_estimator_

# Make predictions on the testing data using the best model
y_pred_best = best_logistic_regression.predict(x_test)

# Calculate accuracy using the best model
accuracy_best = accuracy_score(y_test, y_pred_best)
print("Accuracy with Best Model:", accuracy_best)


Fitting 5 folds for each of 12 candidates, totalling 60 fits
Best Hyperparameters: {'logistic_regression__C': 1, 'logistic_regression__penalty': 'l1'}
Accuracy with Best Model: 0.9582626399728538
